 # -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CamMD.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import cv2 


class Ui_MainWindow(object):


    def __init__(self):
            
            self.Worker1 = Worker1()
            self.Worker1.start()
            self.Worker1.update_image.connect(self.image_update_slot)

    def image_update_slot(self, Image):
            self.camera_box.setPixmap(QtGui.QPixmap.fromImage(Image))

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1059, 615)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: #007EA7;\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.header_rectangle = QtWidgets.QLabel(self.centralwidget)
        self.header_rectangle.setGeometry(QtCore.QRect(0, 0, 1071, 91))
        self.header_rectangle.setStyleSheet("background-color: #022738;")
        self.header_rectangle.setText("")
        self.header_rectangle.setObjectName("header_rectangle")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 10, 291, 81))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("logo.png"))
        self.label.setObjectName("label")
        self.camera_box = QtWidgets.QLabel(self.centralwidget)
        self.camera_box.setGeometry(QtCore.QRect(40, 140, 521, 403))
        self.camera_box.setStyleSheet("background-color: white;")
        self.camera_box.setObjectName("camera_box")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(610, 250, 271, 6))
        self.line.setStyleSheet("background-color: #212121;\n"
"border-radius: 50px;\n"
"")
        self.line.setLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.severity = QtWidgets.QLabel(self.centralwidget)
        self.severity.setGeometry(QtCore.QRect(610, 210, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(20)
        self.severity.setFont(font)
        self.severity.setStyleSheet("background-color: none;")
        self.severity.setObjectName("severity")
        self.output_disease = QtWidgets.QLabel(self.centralwidget)
        self.output_disease.setGeometry(QtCore.QRect(590, 140, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(16)
        self.output_disease.setFont(font)
        self.output_disease.setStyleSheet("background-color: #E5E5E5;\n"
"border-radius: 8px;\n"
"text-align: center;\n"
"padding: 5px;\n"
"\n"
"")
        self.output_disease.setObjectName("output_disease")
        self.treat = QtWidgets.QPushButton(self.centralwidget)
        self.treat.setGeometry(QtCore.QRect(750, 420, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(18)
        self.treat.setFont(font)
        self.treat.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.treat.setStyleSheet("border-radius: 17px;\n"
"background-color: #09BC5B; \n"
"color: white;\n"
"")
        self.treat.setObjectName("treat")
        self.search = QtWidgets.QPushButton(self.centralwidget)
        self.search.setGeometry(QtCore.QRect(590, 490, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(16)
        self.search.setFont(font)
        self.search.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.search.setStyleSheet("border-radius: 17px;\n"
"background-color: #09BC5B; \n"
"color: white;\n"
"")
        self.search.setObjectName("search")
        self.scan_again = QtWidgets.QPushButton(self.centralwidget)
        self.scan_again.setGeometry(QtCore.QRect(760, 490, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(16)
        self.scan_again.setFont(font)
        self.scan_again.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.scan_again.setStyleSheet("border-radius: 17px;\n"
"background-color: #09BC5B; \n"
"color: white;\n"
"")
        self.scan_again.setObjectName("scan_again")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(890, 140, 161, 401))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("doctor_asset.png"))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(590, 200, 311, 281))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(20)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color:#E5E5E5;\n"
"border-radius: 17px;\n"
"")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.severity_message = QtWidgets.QLabel(self.centralwidget)
        self.severity_message.setGeometry(QtCore.QRect(610, 260, 281, 141))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        self.severity_message.setFont(font)
        self.severity_message.setStyleSheet("background-color: none;")
        self.severity_message.setWordWrap(True)
        self.severity_message.setObjectName("severity_message")
        self.label_6.raise_()
        self.label_7.raise_()
        self.header_rectangle.raise_()
        self.label.raise_()
        self.camera_box.raise_()
        self.line.raise_()
        self.severity.raise_()
        self.output_disease.raise_()
        self.treat.raise_()
        self.search.raise_()
        self.scan_again.raise_()
        self.severity_message.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1059, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CamMD"))
        self.camera_box.setText(_translate("MainWindow", "Stream camera here"))
        self.severity.setText(_translate("MainWindow", "SEVERITY:"))
        self.output_disease.setText(_translate("MainWindow", "OUTPUT DISEASE HERE"))
        self.treat.setText(_translate("MainWindow", "Treat >>>"))
        self.search.setText(_translate("MainWindow", "Search"))
        self.scan_again.setText(_translate("MainWindow", "Scan Again"))
        self.severity_message.setText(_translate("MainWindow", "Don’t worry! You don’t have to go see a doctor yet. We’ve got you covered right here!"))

class Worker1(QtCore.QThread):
        update_image = QtCore.pyqtSignal(QtGui.QImage)
        def run(self):
                self.ThreadActive = True
                capture = cv2.VideoCapture(0) # Initialize camera
                while self.ThreadActive:
                        s, frame = capture.read()
                        if s:
                                image = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
                                flipped_image = cv2.flip(image, 1)
                                convert_to_qt = QtGui.QImage(flipped_image.data, flipped_image.shape[1], flipped_image.shape[0], QtGui.QImage.Format_RGB888)
                                picture = convert_to_qt.scaled(521, 403, QtCore.Qt.KeepAspectRatio)
                                self.update_image.emit(picture) 
        















if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
